spring:
  application:
    name: APP-Company
  datasource:
    url: jdbc:h2:mem:company_db
    driver-claas-name: org.h2.Driver
    username: admin
    password: admin
    ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  docker:
    compose:
      enabled: false